version: 1.0.{build}
image: Ubuntu1604
stack: jdk 8
install:
- sh: >-
    old_dir=`pwd`

    set -e

    sudo apt-get update

    sudo apt-get install -y bison python3-pip flex

    cd /usr/local/lib

    sudo wget https://www.antlr.org/download/antlr-4.7.2-complete.jar

    export CLASSPATH=".:/usr/local/lib/antlr-4.7.2-complete.jar:$CLASSPATH"

    antlr4='java -jar /usr/local/lib/antlr-4.7.2-complete.jar'

    cd ~

    wget https://people.csail.mit.edu/asolar/sketch-1.7.5.tar.gz

    tar xvzf sketch-1.7.5.tar.gz

    cd sketch-1.7.5

    cd sketch-backend

    chmod +x ./configure

    ./configure

    make

    cd ..

    cd sketch-frontend

    chmod +x ./sketch

    ./sketch test/sk/seq/miniTest1.sk

    export PATH="$PATH:`pwd`"

    export SKETCH_HOME="`pwd`/runtime"

    cd $old_dir

build_script:
- sh: >-
    set -e

    sudo pip3 install .

    direct_solver example_specs/simple.sk example_alus/stateful_alus/raw.alu example_alus/stateless_alus/stateless_alu.alu 2 2

    direct_solver example_specs/simple.sk example_alus/stateful_alus/raw.alu example_alus/stateless_alus/stateless_alu.alu 2 2 --parallel-sketch

    optverify_stub_generator example_specs/simple.sk example_alus/stateful_alus/raw.alu example_alus/stateless_alus/stateless_alu.alu 1 1 sample1

    optverify_stub_generator example_specs/simple.sk example_alus/stateful_alus/raw.alu example_alus/stateless_alus/stateless_alu.alu 1 1 sample2

    optverify sample1 sample2 example_transforms/very_simple.transform

    $antlr4 chipc/alu.g4 -Dlanguage=Python3 -visitor -package chipc

    direct_solver example_specs/simple.sk example_alus/stateful_alus/raw.alu example_alus/stateless_alus/stateless_alu.alu 2 2 --parallel

    direct_solver example_specs/simple.sk example_alus/stateful_alus/raw.alu example_alus/stateless_alus/stateless_alu.alu 2 2 --parallel --parallel-sketch

    iterative_solver example_specs/simple.sk example_alus/stateful_alus/raw.alu example_alus/stateless_alus/stateless_alu.alu 2 2 10 --hole-elimination

    iterative_solver example_specs/simple.sk example_alus/stateful_alus/raw.alu example_alus/stateless_alus/stateless_alu.alu 2 2 10 --parallel --parallel-sketch --hole-elimination

    python3 -m unittest

    echo "********ALL DONE*******"
